export const pricingPlans = [
  {
    type: "Monthly Plan",
    price: "₹300",
    subscription: "month",
    description: "Short-term commitment, long-term benefits",
    buttonText: "Oh, you're cheap like that!",
    planId: "plan_OTfcOwTpNeN7tZ",
    free_trial: 7 * 24 * 60 * 60, // one week in seconds
    discountPlanId: "plan_OZdR9rsKa7uyA6",
    discountPrice: "₹240",
    total_count: 9,
    features: [
      "7-days free trial",
      "Access to all features",
      "Add a partner for free",
    ],
  },
  {
    type: "3-Month Plan",
    price: "₹700",
    subscription: "year",
    description: "Flexibility for the cautious planner",
    buttonText: "Getting Warmer!",
    planId: "plan_OTfeA9ulkvC9KV",
    free_trial: 14 * 24 * 60 * 60,
    total_count: 3,
    discountPlanId: "plan_OZdRqaBH3qdIn5",
    discountPrice: "₹560",
    features: [
      "14-day free trail",
      "Access to all features",
      "Add a partner for free",
    ],
  },
  {
    type: "One-Time Payment",
    price: "₹1800",
    subscription: "",
    description: "One payment, endless peace of mind",
    buttonText: "Genius Move!",
    active: true,
    planId: "plan_OTffcoJtdpZPsZ",
    free_trial: 30 * 24 * 60 * 60,
    total_count: 1,
    discountPlanId: "plan_OZdSYxhn9fQUbf",
    discountPrice: "₹1440",
    features: [
      "1-month free trial",
      "Access to all features",
      "Add a partner for free",
      "Use for multiple children",
    ],
  },
];
