name: Deploy Admin to Amazon ECS

on:
  push:
    branches:
      - 'main'
    paths:
      - 'admin/**'

defaults:
  run:
    working-directory: admin

jobs:
  deploy:
    name: Deploy Admin to EC2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: 'Build'
        run: npm run build --if-present

      - name: Deploy EC2
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: 'admin/'
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: 'admin/node_modules/'
